config/routes.rb
Rails.application.routes.draw do
  get '/pets/new' => 'pets#new', as: :new_pet
  get '/pets' => 'pets#index', as: :pets
  get '/pets/:id' => 'pets#show', as: :pet
  get '/pets/:id/edit' => 'pets#edit', as: :edit_pet
  post '/pets' => 'pets#create'
  patch '/pets/:id' => 'pets#update'
  delete '/pets/:id' => 'pets#destroy'

  get '/mobile' => 'application#mobile'
  get '/nope' => 'application#nope'

  get '/sessions/new' => 'sessions#new', as: :new_sessions
  post '/sessions' => 'sessions#create', as: :session
  delete '/sessions' => 'sessions#destroy'

end

app/models/pet.rb
class Pet < ActiveRecord::Base
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  before_action :ensure_user_signed_in

  before_action :ensure_user_not_mobile, except: :mobile

  def mobile
    render text: 'You cannot view the requested page from a mobile device.'
  end

  def ensure_user_not_mobile
    if request.user_agent =~ /mobile/
      redirect_to controller: 'application', action: 'mobile'
    end
  end

  def nope
    render text: 'You cannot delete stuff.'
  end

  private

  def ensure_user_signed_in
    unless current_user.present?
      redirect_to new_sessions_path, alert: 'Must be signed in'
    end
  end

  def current_user
    if session.has_key? :user_id
      @current_user ||= User.find(session[:user_id])
    end
  end

  helper_method :current_user

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  skip_before_action :ensure_user_not_mobile, only: :index
  #before_action :prevent_remote_delete, only: :destroy

  def prevent_remote_delete
    unless request.remote_ip =~ /127\.0\.0\.1/ 
      redirect_to controller: 'application', action: 'nope'
    end
  end

  def index
    @pets = Pet.all.decorate
  end

  def show
    @pet = Pet.find(params[:id]).decorate
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)

    if @pet.save
      flash[:notice] = "Pet created successfully!"
      redirect_to pet_path(@pet)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])

    if @pet.update(pet_params)
      flash[:notice] = "Pet updated successfully!"
      redirect_to pet_path(@pet)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    pet = Pet.find(params[:id])
    pet.destroy
    redirect_to pets_path
  end

  private 

  def pet_params
    params.require(:pet).permit(:name, :breed, :color, :last_seen_at)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :ensure_user_signed_in, only: [:new, :create]

  # Present login form
  def new
  end

  # Create session
  def create
    user = User.where(email: params[:email]).first
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to pets_path
    else
      redirect_to new_sessions_path, alert: 'Unable to authenticate'
    end
  end

  # Logout
  def destroy
    reset_session
    redirect_to new_sessions_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
  def color_to_class(color)
    "color-#{color}"
  end

  def pretty_text_field(f,field)
    content_tag(:div, nil, class: 'form-group') do |content|
      f.label(field) + ' ' + f.text_field(field, :class => 'form-control')
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LostDog</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: name %>
<% end %>

<% if current_user.present? %>
  <nav class="navbar navbar-default">
    <div class="container">
    <p class="navbar-text">Signed in as <%= current_user.email %></p>
    
    <%= link_to "Sign Out", sessions_path, method: :delete, :class => 'btn btn-default navbar-btn' %>
    </div>
  </nav>
<% end %>

<div class="container">

<%= yield %>

</div><!-- end of container -->

</body>
</html>

app/views/pets/_form.html.erb
<%= form_for(pet) do |f| %>
  <% if pet.errors.any? %>
    <ul>
      <% pet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  
  <%= pretty_text_field(f, :name) %>
  <%= pretty_text_field(f, :breed) %>

  <div class="form-group">
    <%= f.label :color %>
    <%= f.select :color, ['black', 'white', 'spotted', 'brindle'], {}, {:class => 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.label :last_seen_at %>
    <%= f.datetime_select :last_seen_at %>
  </div>
  
  <%= f.submit :class => 'btn btn-primary' %>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing Your Pet</h1>

<%= render 'form', pet: @pet %>

app/views/pets/index.html.erb
<h1>All Pets</h1>

<div>
  <%= link_to "Create a new entry", new_pet_path %>
</div>

<table class="table">
  <thead>
    <tr>
      <td>Name</td>
      <td>Breed</td>
      <td>Color</td>
      <td>Last Seen</td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %></td>
        <td><%= pet.breed %></td>
        <td><%= pet.color %></td>
        <td><%= pet.last_seen_at %></td>
        <td>
          <%= link_to "View", pet_path(pet) %> | 
          <%= link_to "Edit", edit_pet_path(pet) %> |
          <%= link_to "Delete", pet_path(pet), method: :delete, data: { confirm: "Are you sure?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form', pet: @pet %>

app/views/pets/show.html.erb
<h1><%= @pet.name %></h1>

<dl>
  <dt>Breed</dt>
  <dd><%= @pet.breed %></dd>

  <dt>Color</dt>
  <dd class="<%= color_to_class(@pet.color) %>"><%= @pet.color %></dd>

  <dt>Last Seen</dt>
  <dd><%= time_ago_in_words @pet.last_seen_at %> ago</dd>
</dl>

<div>
  <%= link_to "Edit", edit_pet_path(@pet), {:class => 'btn btn-default'} %>
</div>

<div>
  <%= link_to "Delete", pet_path(@pet), method: :delete, data: { confirm: "Are you sure?" } %>
</div>

<div>
  <%= link_to "Show All", pets_path, {:class => 'btn btn-default'} %>
</div>